name: Result Kt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: kmartins/workflows/.github/workflows/dart_package.yaml@dart_package-v1.0.0

  pana:
    uses: kmartins/workflows/.github/workflows/pana.yaml@pana-v1.0.2
